---
title: "Women in Workplace"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(glue)
library(plotly)
```

```{r}
workers <- read.csv("data_input/jobs_gender.csv")
```

```{r}
workers_clean <- workers %>% 
  mutate_if(is.character, as.factor) %>% 
  mutate(year = as.factor(year))
```

```{r}
workers_clean <- workers_clean %>% 
  select(-wage_percent_of_male) %>% 
  drop_na(total_earnings_male, total_earnings_female)
```

```{r}
# Persiapan data yang sudah diaggre

case1 <- workers_clean %>% 
  mutate(gap_earning = total_earnings_male - total_earnings_female) %>% 
  filter(year == 2016) %>% 
  group_by(major_category) %>% 
  summarise(mean_gap_earning = mean(gap_earning)) %>% 
  ungroup()

case2 <- workers_clean %>% 
  filter(workers_female > workers_male) %>% 
  group_by(major_category) %>% 
  summarise(n_position = n()) %>% 
  arrange(desc(n_position))

case3 <- workers_clean %>% 
  filter(year == 2016) %>% 
  pivot_longer(cols = c("total_earnings_male", "total_earnings_female"), 
               names_to = "gender", 
               values_to = "total_earnings_male_female",
               names_prefix = "total_earnings_") %>% 
  select(gender, total_earnings_male_female)
```

Overview
===

## Row {data-width="350"}

### Mean Gap Earning of Female vs Male in 2016

```{r}
library(ggthemes)
plot_case1 <- case1 %>% 
  ggplot(aes(x = mean_gap_earning, 
             y = reorder(major_category, mean_gap_earning),
             text = glue("Mean Gap Earning: {round(mean_gap_earning, 2)}")))+
  geom_col(aes(fill = mean_gap_earning), show.legend = F) + 
  scale_fill_gradient(low="#fff2cd", high="firebrick") + 
  labs(title = "Mean Gap Earning", 
       subtitle = "Pegawai Laki-laki dan Perempuan Tahun 2016",
       x = "Mean Gap Earning", 
       y = "Divisi") +
  theme_clean()
```

```{r}
ggplotly(plot_case1, tooltip = "text")
```

### Chart C

```{r}
plot_case2 <- case2 %>% 
  ggplot(aes(x = n_position,
             y = reorder(major_category, n_position),
             text = glue("Jumlah Posisi Divisi: {n_position}"))) +
  geom_segment(aes(x = 0, xend=n_position, yend= major_category), color="grey") +
  geom_point(color="firebrick", size=2.5, alpha=0.6) +
  theme(
    panel.grid.major.y = element_blank(),
    panel.border = element_blank(),
    axis.ticks.y = element_blank()
  ) + 
  labs(title = "Jumlah Divisi", 
       subtitle = "Pegawai Perempuan",
       x = "Jumlah Posisi Divisi", 
       y = "Divisi") +
  theme_bw()
```

```{r}
ggplotly(plot_case2, tooltip = "text")
```


## Row {data-height="400"}

### Dataset of Women in Workplace

```{r}
library(DT)
datatable(workers_clean)
```


Distribution
===

Row
---

### Distribution Total Earning of Male vs Female in 2016

```{r}
options(scipen = 99)
plot_case3 <- case3 %>% 
  ggplot(aes(x = total_earnings_male_female)) + 
  geom_density(aes(fill=gender, position = "identity", alpha = 0.8)) + 
  theme_clean() +
  labs(
    title = "Sebaran Pendapatan Berdasarkan Gender", x = NULL, y = NULL
  ) + 
  scale_fill_brewer(palette = "Set2")
```
```{r}
ggplotly(plot_case3, tooltip = "x")
```




